<?php echo $this->doctype(); ?>
<html lang="pt">
<head>
    <meta charset="utf-8"/>



    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1')
    ?>

    <!-- basic styles -->

    <?php
    $this->placeholder('basic-styles')->setSeparator(chr(13));
    $this->placeholder('basic-styles')->prepend(
        '   <link href="' . $this->basePath() . '/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        '
    );

    echo $this->placeholder('basic-styles');

    $this->placeholder('specific-plugin-styles')->setSeparator(chr(13));
    $this->placeholder('specific-plugin-styles')->prepend(
        '
            <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300" rel="stylesheet" type="text/css">
            <link href="' . $this->basePath() . '/assets/css/ace.min.css" rel="stylesheet" type="text/css">
            <link href="' . $this->basePath() . '/assets/css/ace-skins.min.css" rel="stylesheet" type="text/css">
            <link href="' . $this->basePath() . '/assets/css/ace-fonts.css" rel="stylesheet" type="text/css">

            <!--[if lte IE 9]>
                <link rel="stylesheet" href="' . $this->basePath() . '/assets/css/ace-part2.min.css" />
            <![endif]-->

            <link href="' . $this->basePath() . '/assets/css/ace-rtl.min.css" rel="stylesheet" type="text/css">

            <!--[if lte IE 9]>
		        <link rel="stylesheet" href="' . $this->basePath() . '/assets/css/ace-ie.min.css" />
		    <![endif]-->

		    <!--[if lt IE 9]>
            <script src="' . $this->basePath() . '/assets/js/html5shiv.js"></script>
            <script src="' . $this->basePath() . '/assets/js/respond.min.js"></script>
            <![endif]-->

        '
    );
    echo $this->placeholder('specific-plugin-styles');
    ?>

    <?php
    $this->placeholder('default-layout-scripts')->setSeparator(chr(13));
    $this->placeholder('default-layout-scripts')->prepend(
        '
            <script type="text/javascript" src="' . $this->basePath() . '/assets/js/ace-extra.min.js"></script>
            <!--[if lt IE 8]><script type="text/javascript" src="' . $this->basePath() . '/assets/js/html5shiv.js"></script><![endif]-->
            <!--[if lt IE 8]><script type="text/javascript" src="' . $this->basePath() . '/assets/js/respond.min.js"></script><![endif]-->
        '
    );
    echo $this->placeholder('default-layout-scripts');
    ?>

</head>
<body class="login-layout">
<div class="main-container">
    <div class="main-content">
        <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
                <div class="login-container">
                    <?php echo $this->content; ?>
                </div>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div>
</div><!-- /.main-container -->



<script type="text/javascript">
    window.jQuery || document.write("<script src='<?php echo $this->basePath() ?>/assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
</script>

<!-- <![endif]-->

<!--[if IE]>
<script type="text/javascript">
    window.jQuery || document.write("<script src='<?php echo $this->basePath() ?>/assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

<script type="text/javascript">
    if("ontouchend" in document) document.write("<script src='<?php echo $this->basePath() ?>/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
</script>

<script src="<?php echo $this->basePath() ?>/assets/js/bootstrap.min.js"></script>
<script src="<?php echo $this->basePath() ?>/assets/js/typeahead-bs2.min.js"></script>

<script src="<?php echo $this->basePath() ?>/assets/js/jquery.maskedinput.min.js"></script>

<!--[if lte IE 8]>
<script src="<?php echo $this->basePath() ?>/assets/js/excanvas.min.js"></script>
<![endif]-->
</body>
</html>