<?php foreach ($imovel as $index => $itemImovel) { ?>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $itemImovel['nome']; ?></h3>
            </div>
            <div class="panel-body">
                <p>
                    <img src="data:<?php echo $itemImovel['imageBase64']['contentType']?>; base64, <?php echo $itemImovel['imageBase64']['body']?>">
                </p>
                <p>
                    <a class="btn btn-success pull-left">Comprar</a>
                </p>
                <p>
                    <a class="btn btn-success pull-right"
                      onclick="buscarImoveisProximos(<?php echo $itemImovel['latitude']; ?>,
                                                     <?php echo $itemImovel['longitude']; ?>)">Imoveis nas próximidades
                    </a>
                </p>
            </div>
        </div>
    </div>
<?php } ?>

<div id="imoveis-proximos"></div>

<script>

    function buscarImoveisProximos(latitude, longitude) {
        $.ajax({
            url: "/imoveisNasProximidades",
            type: 'get',
            data: {
                'latitude': latitude,
                'longitude': longitude
            },
            dataType: 'html',
            beforeSend: function () {
                $('#imoveis-proximos').html('<button class="btn btn-lg btn-warning"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading...</button>');
            },
            cache: false,
            success: function (data) {
                $('#imoveis-proximos').html(data);

            },
            error: function (request) {
                $('#imoveis-proximos').html('erro');

            }
        })
    }

</script>

