<p>
<center>
    <a href="/listarTodosImoveis" title="Listar todos imoveis">
        <i class="fa fa-edit"></i>
        <button type="button"
                class="width-35 pull-left btn btn-sm btn-primary bootbox-options">
            <i class="ace-icon fa fa-key"></i>
            Listar todos imoveis
        </button>
    </a>

    <form class="navbar-form " role="search">
        <div class="form-group">
            <input type="text" id="imovel-nome" name="imovel-nome" class="form-control" placeholder="Pesquisar">
        </div>
        <button type="button" onclick="buscarImovel()" class="btn btn-default">Pesquisar</button>
    </form>
    <div id="loading"></div>
</center>
</p>


<script>

    function buscarImovel() {
        $.ajax({
            url: "/imovel",
            type: 'get',
            data: $('#imovel-nome').serialize(),
            dataType: 'html',
            beforeSend: function () {
                $('#loading').html('<button class="btn btn-lg btn-warning"><span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Loading...</button>');
            },
            cache: false,
            success: function (data) {
                $('#loading').html(data);

            },
            error: function (request) {
                $('#loading').html('erro');

            }
        })
    }

</script>
